### ISSUE TITLE
Control cell line data for Cmap

### ISSUE THREAD

**Issue by shaman-narayanasamy** [cran/DrInsight#2]
Dear authors/developers,

My name is Shaman Narayanasamy, a researcher from University of Luxembourg. First off, congratulations on the development of DrInsight. It is a great tool/resource!

My colleagues and I are currently working on the Cmap v2 build for a drug repurposing project and would like to complement the findings from DrInsight with output from commercial tools that are available to us. We are unfortunately unable to identify the control/baseline cell line samples. We searched for the relevant information on [the CLUE platform](https://clue.io/data/CMB02#B02), the original publication (and supplementary information) by Lamb et al. (2006) and independent [alternative platforms](https://maayanlab.cloud/Harmonizome/dataset/CMAP+Signatures+of+Differentially+Expressed+Genes+for+Small+Molecules). Whole we are able to find the raw microarray data on some of those resources, we are unable to identify which of the experiments are control cell line data (i.e. within the [cmap_instances_02.xls](https://clue.io/data/CMB02#) table). 

We are hoping that you would be able to point us to the resource for the control/baseline cell line data, preferably the raw microarray data, as DrInsight relies on such information for the analysis.

I apologise in advance if we potentially missed any information on this matter. Please do not hesitate to ask us any further questions. We look forward to your response.

Best regards,
Shaman

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by shaman-narayanasamy** [comment]
Hi, Apologies for the confusion. Thank you for the information!
